# Base image
FROM python:3.8-slim

# Set working directory
WORKDIR /app

# Copy dependencies
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY src/ ./src/

# Expose port (variable PORT di docker-compose)
ARG PORT
EXPOSE ${PORT}

# Default command di docker-compose.yml (uvicorn dijalankan di sana)
